<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="0Harmony">
			<HintPath>ArcaxerDLLS\0Harmony.dll</HintPath>
		</Reference>
		<Reference Include="Assembly-CSharp">
			<HintPath>ArcaxerDLLS\Assembly-CSharp.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppInterop.Common">
			<HintPath>ArcaxerDLLS\Il2CppInterop.Common.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppInterop.Generator">
			<HintPath>ArcaxerDLLS\Il2CppInterop.Generator.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppInterop.Runtime">
			<HintPath>ArcaxerDLLS\Il2CppInterop.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Il2Cppmscorlib">
			<HintPath>ArcaxerDLLS\Il2Cppmscorlib.dll</HintPath>
		</Reference>
		<Reference Include="MelonLoader">
			<HintPath>ArcaxerDLLS\MelonLoader.dll</HintPath>
		</Reference>
		<Reference Include="Newtonsoft.Json">
			<HintPath>ArcaxerDLLS\Newtonsoft.Json.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine">
			<HintPath>ArcaxerDLLS\UnityEngine.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>ArcaxerDLLS\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ImageConversionModule">
			<HintPath>ArcaxerDLLS\UnityEngine.ImageConversionModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.JSONSerializeModule">
			<HintPath>ArcaxerDLLS\UnityEngine.JSONSerializeModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TextRenderingModule">
			<HintPath>ArcaxerDLLS\UnityEngine.TextRenderingModule.dll</HintPath>
		</Reference>
	</ItemGroup>
</Project>